# Data Prepration

In [2]:
import pandas as pd 
import sqlite3

In [3]:
# creating connection
conn = sqlite3.connect('../inventory.db')

In [4]:
# checking tables present in the database 
tables = pd. read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", conn) 

tables

              name
0  begin_inventory
1    end_inventory
2        purchases
3  purchase_prices
4            sales
5   vendor_invoice

In [5]:
import pandas as pd

# Assuming 'conn' is your active sqlite3 connection
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
print(tables)

              name
0  begin_inventory
1    end_inventory
2        purchases
3  purchase_prices
4            sales
5   vendor_invoice

**Checking DB**

In [6]:
import os
import sqlite3
import pandas as pd

print(f"1. Current Working Directory: {os.getcwd()}")
print(f"2. Does 'inventory.db' exist here?: {os.path.exists('inventory.db')}")

# Connect directly to the database in this specific folder
conn = sqlite3.connect('inventory.db')

# Query the database to see what tables it actually holds
tables_query = "SELECT name FROM sqlite_master WHERE type='table';"
tables_df = pd.read_sql(tables_query, conn)

print("\n3. Tables currently in this database:")
if tables_df.empty:
    print("   [WARNING: The database is completely EMPTY!]")
else:
    print(tables_df)
    
conn.close()

1. Current Working Directory: c:\Users\6035s\Desktop\MLOPS\Vendor-Performance-Analysis\notebook
2. Does 'inventory.db' exist here?: True

3. Tables currently in this database:
   [WARNING: The database is completely EMPTY!]

EDA

In [7]:
import pandas as pd
import sqlite3

# 1. Connect to the correct database (using the 'up one folder' path we fixed earlier)
conn = sqlite3.connect('../inventory.db')

# 2. Re-fetch the tables directly into a brand new DataFrame variable
tables_query = "SELECT name FROM sqlite_master WHERE type='table';"
tables_df = pd.read_sql(tables_query, conn)

# 3. Loop through our fresh DataFrame
if tables_df.empty:
    print("The database is empty! Please check your ingestion script.")
else:
    for table in tables_df['name']: 
        print(f"\n{'-'*20} {table} {'-'*20}") 
        
        # Wrapping the table name in double quotes prevents SQL syntax errors
        query = f'SELECT COUNT(*) as count FROM "{table}"'
        
        count_df = pd.read_sql(query, conn)
        record_count = count_df['count'].values[0]
        
        print(f"Count of records: {record_count}")

# 4. Good practice: close the connection when done probing
conn.close()

-------------------- begin_inventory --------------------
Count of records: 206529

-------------------- end_inventory --------------------
Count of records: 224489

-------------------- purchases --------------------
Count of records: 2372474

-------------------- purchase_prices --------------------
Count of records: 12261

-------------------- sales --------------------
Count of records: 12825363

-------------------- vendor_invoice --------------------
Count of records: 5543

In [8]:
import pandas as pd
import sqlite3

# 1. Connect to the database
conn = sqlite3.connect('../inventory.db')

# 2. Fetch the table names into a safely named DataFrame variable
tables_df = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)

# 3. Loop through the safe variable
for table in tables_df['name']:
    
    # Note: We still wrap "{table}" in quotes in the SQL strings just in case a table name has spaces
    count = pd.read_sql(f'SELECT count(*) as count FROM "{table}"', conn)['count'].values[0]
    
    print('Count of records:', count) 
    print(f"\n{'-'*20} {table} {'-'*20}") 
    
    # Your new display logic, also protected with double quotes around the table name
    display(pd.read_sql(f'SELECT * FROM "{table}" LIMIT 5', conn))

# Close connection when done
# conn.close()

Count of records: 206529

-------------------- begin_inventory --------------------

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

Count of records: 224489

-------------------- end_inventory --------------------

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

Count of records: 2372474

-------------------- purchases --------------------

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

Count of records: 12261

-------------------- purchase_prices --------------------

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

Count of records: 12825363

-------------------- sales --------------------

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

Count of records: 5543

-------------------- vendor_invoice --------------------

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [9]:
purchases = pd. read_sql_query("select * from purchases where VendorNumber = 4466", conn) 
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [10]:
purchases.groupby(['Brand' ,'PurchasePrice'])[ ['Quantity', 'Dollars' ]].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [11]:
purchase_prices = pd.read_sql_query('SELECT * FROM "purchase_prices"',conn)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.
...,...,...,...,...,...,...,...,...,...
12256,44917,Ferreira 10-Yr Tawny Port,24.99,750mL,750,2,16.55,90024,VINILANDIA USA
12257,44944,Sanford Santa Rita Pnt Nr,22.99,750mL,750,2,14.93,4425,MARTIGNETTI COMPANIES
12258,45016,Neal One Lane Bridg Cab Svgn,93.99,750mL,750,2,61.43,10754,PERFECTA WINES
12259,46011,Folonari Pnt Nr Venezie,12.99,1500ml,1500,2,8.90,9744,FREDERICK WILDMAN & SONS
12260,46964,Calera Viognier Mt Harlan,35.99,750mL,750,2,24.32,10754,PERFECTA WINES

In [12]:
# Assuming you have an active connection named 'conn'
vendor_invoice = pd.read_sql_query('SELECT * FROM "vendor_invoice"', conn) 

# Now you can display it
display(vendor_invoice)

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None
...,...,...,...,...,...,...,...,...,...,...
5538,9622,WEIN BAUER INC,2025-01-06,13626,2024-12-21,2025-02-10,90,1563.00,8.60,None
5539,9625,WESTERN SPIRITS BEVERAGE CO,2025-01-10,13661,2024-12-23,2025-02-18,4617,37300.48,186.50,None
5540,3664,WILLIAM GRANT & SONS INC,2025-01-02,13643,2024-12-22,2025-02-04,9848,202815.78,932.95,None
5541,9815,WINE GROUP INC,2025-01-03,13602,2024-12-20,2025-02-08,24747,149007.56,819.54,None
5542,90058,ZORVINO VINEYARDS,2025-01-05,13574,2024-12-18,2025-02-12,437,3608.11,16.60,None

In [13]:
vendor_invoice['PONumber'].nunique()

5543

In [14]:
vendor_invoice.shape

(5543, 10)

In [15]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [16]:
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [17]:
sales = pd.read_sql_query('SELECT * FROM "sales"', conn) 

# Now you can display it
display(sales)

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12825358,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-17,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
12825359,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-21,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
12825360,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,3,77.97,25.99,2024-12-23,750.0,1,2.36,9165,ULTRA BEVERAGE COMPANY LLP
12825361,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-24,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
12825362,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,2,51.98,25.99,2024-12-29,750.0,1,1.57,9165,ULTRA BEVERAGE COMPANY LLP

In [18]:
sales.groupby('Brand' ) [['SalesDollars','SalesPrice','SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
58         43341.54    28145.64           3446
60         18716.25    10720.79           1775
61          4364.88      363.74            312
62        119863.75    90154.51           3125
63        112249.22    88553.10           2778
...             ...         ...            ...
90089      19078.41     5759.52            159
90090       9749.85     4549.93             15
90604       9119.24     2639.78             76
90609       2074.17     1774.29             83
90631      31504.41    19502.73           1659

[11237 rows x 3 columns]

In [19]:
freight_summary = pd.read_sql_query("""select VendorNumber, SUM(Freight) as FreightCost From vendor_invoice Group BY VendorNumber""", conn)

In [20]:
freight_summary

     VendorNumber  FreightCost
0               2        27.08
1              54         0.48
2              60       367.52
3             105        62.39
4             200         6.19
..            ...          ...
121         98450       856.02
122         99166       130.09
123        172662       178.34
124        173357       202.50
125        201359         0.09

[126 rows x 2 columns]

In [21]:
pd. read_sql_query("""SELECT 
p.VendorNumber, 
p.VendorName, 
p.Brand, 
p.PurchasePrice, 
pp.Volume, 
pp.Price as ActualPrice, 
SUM(p.Quantity) as TotalPurchaseQuantity, 
SUM(p.Dollars) as TotalPurchaseDollars 
FROM purchases p 
JOIN purchase_prices pp 
ON p.Brand = pp.Brand GROUP BY 
p. VendorNumber, p.VendorName, p.Brand 
ORDER BY TotalPurchaseDollars""",conn)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,2561,EDRINGTON AMERICAS,2166,0.00,750,0.00,2015,0.00
1,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1,0.71
2,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1,1.47
3,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2,1.48
4,8004,SAZERAC CO INC,5683,0.39,50,0.49,6,2.34
...,...,...,...,...,...,...,...,...
10688,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109,3023206.01
10689,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682,3261197.94
10690,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407,3418303.68
10691,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038,3804041.22
10692,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080,3811251.60

In [22]:
pd.read_sql_query("""SELECT 
p.VendorNumber, 
p.VendorName, 
p.Brand, 
p.PurchasePrice, 
pp.Volume, 
pp.Price as ActualPrice, 
SUM(p.Quantity) as TotalPurchaseQuantity, 
SUM(p.Dollars) as TotalPurchaseDollars 
FROM purchases p 
JOIN purchase_prices pp ON 
p.Brand = pp.Brand 
Where p.PurchasePrice > 0
GROUP BY p.VendorNumber, p.VendorName, p.Brand
ORDER BY TotalPurchaseDollars""",conn)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2,1.48
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,6,2.34
4,9815,WINE GROUP INC,8527,1.32,750,4.99,2,2.64
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682,3261197.94
10689,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080,3811251.60

In [23]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [24]:
pd.read_sql_query("""SELECT 
VendorNo, 
Brand, 
SUM(SalesDollars) as TotalSalesDollars, 
SUM(SalesPrice) as TotalSalesPrice, 
SUM(SalesQuantity) as TotalSalesQuanity, 
SUM(ExciseTax) as TotalExciseTax 
FROM sales 
GROUP BY VendorNo, Brand""", conn)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuanity,TotalExciseTax
0,2,90085,665.82,295.92,18,2.00
1,2,90609,599.76,449.82,24,0.52
2,60,771,704.53,494.67,47,37.01
3,60,3979,66871.69,41682.51,3931,7224.06
4,105,2529,359.88,59.98,12,9.44
...,...,...,...,...,...,...
11267,173357,2804,6298.60,3194.29,140,110.33
11268,173357,3666,8996.40,4873.05,360,141.19
11269,173357,3848,185.94,92.97,6,4.71
11270,173357,3909,24540.18,14469.21,982,773.87
11271,201359,90609,1474.41,1324.47,59,1.24

In [25]:
# import time 
# start = time.time() 
# final_table = pd. read_sql_query("""SELECT 
#     pp.VendorNumber, 
#     pp.Brand, 
#     pp.Price as Actl, 
#     pp.PurchasePrice, 
#     SUM(s.SalesQuantity) AS TotalSalesQuantity, 
#     SUM(s.SalesDollars) AS TotalSalesDollars, 
#     SUM(s.SalesPrice) AS TotalSalesPrice, 
#     SUM(s.ExciseTax) AS TotalExciseTax, 
#     SUM(vi.Quantity) AS TotalPurchaseQuantity, 
#     SUM(vi.Dollars) AS TotalPurchaseDollars, 
#     SUM(vi. Freight) AS TotalFreightCost 
# FROM purchase_prices pp 
# JOIN sales s 
#    ON pp. VendorNumber = s. VendorNo 
#    AND pp.Brand = s.Brand 
# JOIN vendor_invoice vi 
#    ON pp. VendorNumber = vi. VendorNumber 
#    GROUP BY pp. VendorNumber, pp.Brand, pp.Price, pp.PurchasePrice""",conn)

# end = time.time()

In [26]:
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None
...,...,...,...,...,...,...,...,...,...,...
5538,9622,WEIN BAUER INC,2025-01-06,13626,2024-12-21,2025-02-10,90,1563.00,8.60,None
5539,9625,WESTERN SPIRITS BEVERAGE CO,2025-01-10,13661,2024-12-23,2025-02-18,4617,37300.48,186.50,None
5540,3664,WILLIAM GRANT & SONS INC,2025-01-02,13643,2024-12-22,2025-02-04,9848,202815.78,932.95,None
5541,9815,WINE GROUP INC,2025-01-03,13602,2024-12-20,2025-02-08,24747,149007.56,819.54,None
5542,90058,ZORVINO VINEYARDS,2025-01-05,13574,2024-12-18,2025-02-12,437,3608.11,16.60,None

In [27]:
vendor_sales_summary = pd.read_sql_query("""WITH FreightSummary AS  ( 
 SELECT 
                                         VendorNumber, 
                                         SUM(Freight) AS FreightCost 
                                         FROM vendor_invoice GROUP BY VendorNumber ),

PurchaseSummary AS ( 
                                         SELECT 
                                         p.VendorNumber, 
                                         p.VendorName, 
                                         p.Brand, 
                                         p.Description, 
                                         p.PurchasePrice, 
                                         pp.Price AS ActualPrice, 
                                         pp.Volume, 
                                         SUM(p.Quantity) AS TotalPurchaseQuantity, 
                                         SUM(p.Dollars) AS TotalPurchaseDollars 
                                         FROM purchases p 
                                         JOIN purchase_prices pp 
                                         ON p.Brand = pp.Brand 
                                         WHERE p. PurchasePrice > 0 
                                         GROUP BY p.VendorNumber, p.VendorName, p.Brand, p.Description, p.PurchasePrice, pp.Price, pp.Volume ),          


SalesSummary AS ( 
                                         SELECT 
                                         VendorNo, 
                                         Brand, 
                                         SUM(SalesQuantity) AS TotalSalesQuantity,                                         
                                         SUM(SalesDollars) AS TotalSalesDollars, 
                                         SUM(SalesPrice) AS TotalSalesPrice, 
                                         SUM(ExciseTax) AS TotalExciseTax 
                                         FROM sales 
                                         GROUP BY VendorNo, Brand )



SELECT 
                                         ps.VendorNumber, 
                                         ps.VendorName, 
                                         ps.Brand, 
                                         ps.Description, 
                                         ps.PurchasePrice, 
                                         ps.ActualPrice, 
                                         ps.Volume, 
                                         ps.TotalPurchaseQuantity, 
                                         ps.TotalPurchaseDollars,
                                         ss.TotalSalesQuantity, 
                                         ss. TotalSalesDollars, 
                                         ss.TotalSalesPrice, 
                                         ss.TotalExciseTax, 
                                         fs.FreightCost 
                                         FROM PurchaseSummary ps 
                                         LEFT JOIN SalesSummary ss 
                                         ON ps. VendorNumber = ss. VendorNo 
                                         AND ps.Brand = ss.Brand 
                                         LEFT JOIN FreightSummary fs 
                                         ON ps. VendorNumber = fs. VendorNumber 
                                         ORDER BY ps. TotalPurchaseDollars DESC""", conn)

In [28]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750,2,2.64,5.0,15.95,10.96,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50,6,2.34,134.0,65.66,1.47,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50,2,1.48,2.0,1.98,0.99,0.10,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200,1,1.47,72.0,143.28,77.61,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50,1,0.71,86.0,85.14,33.66,4.46,38994.78

### EDA

In [39]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
ActualPrice              float64
Volume                   float64
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [30]:
vendor_sales_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10692 entries, 0 to 10691
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorNumber           10692 non-null  int64
 1   VendorName             10692 non-null  object
 2   Brand                  10692 non-null  int64
 3   Description            10692 non-null  object
 4   PurchasePrice          10692 non-null  float64
 5   ActualPrice            10692 non-null  float64
 6   Volume                 10692 non-null  object
 7   TotalPurchaseQuantity  10692 non-null  int64
 8   TotalPurchaseDollars   10692 non-null  float64
 9   TotalSalesQuantity     10514 non-null  float64
 10  TotalSalesDollars      10514 non-null  float64
 11  TotalSalesPrice        10514 non-null  float64
 12  TotalExciseTax         10514 non-null  float64
 13  FreightCost            10692 non-null  float64
dtypes: float64(8), int64(3), object(3)
memory usage: 1.1+ MB

In [32]:
vendor_sales_summary.describe()

,VendorNumber,Brand,PurchasePrice,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
count,10692.000000,10692.000000,10692.000000,10692.000000,10692.000000,1.069200e+04,10514.000000,1.051400e+04,10514.000000,10514.000000,10692.000000
mean,10650.649458,18039.228769,24.385303,35.643671,3140.886831,3.010669e+04,3129.583317,4.295417e+04,19111.958773,1804.263569,61433.763214
std,18753.519148,12662.187074,109.269375,148.246016,11095.086769,1.230678e+05,11037.801407,1.689778e+05,45264.605387,11065.659557,60938.458032
min,2.000000,58.000000,0.360000,0.490000,1.000000,7.100000e-01,1.000000,1.980000e+00,0.990000,0.060000,0.090000
25%,3951.000000,5793.500000,6.840000,10.990000,36.000000,4.534575e+02,36.000000,8.098200e+02,334.890000,5.382500,14069.870000
50%,7153.000000,18761.500000,10.455000,15.990000,262.000000,3.655465e+03,280.000000,5.599700e+03,3020.085000,50.425000,50293.620000
75%,9552.000000,25514.250000,19.482500,28.990000,1975.750000,2.073825e+04,1985.000000,2.952425e+04,16442.477500,436.730000,79528.990000
max,201359.000000,90631.000000,5681.810000,7499.990000,337660.000000,3.811252e+06,334939.000000,5.101920e+06,672819.310000,368242.800000,257032.070000

In [31]:
vendor_sales_summary.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
ActualPrice                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
TotalSalesQuantity       178
TotalSalesDollars        178
TotalSalesPrice          178
TotalExciseTax           178
FreightCost                0
dtype: int64

In [38]:
vendor_sales_summary ['VendorName' ].unique()

array(['BROWN-FORMAN CORP', 'MARTIGNETTI COMPANIES', 'PERNOD RICARD USA',
       'DIAGEO NORTH AMERICA INC', 'BACARDI USA INC',
       'JIM BEAM BRANDS COMPANY', 'MAJESTIC FINE WINES',
       'ULTRA BEVERAGE COMPANY LLP', 'STOLI GROUP,(USA) LLC',
       'PROXIMO SPIRITS INC.', 'MOET HENNESSY USA INC', 'CAMPARI AMERICA',
       'SAZERAC CO INC', 'CONSTELLATION BRANDS INC', 'M S WALKER INC',
       'SAZERAC NORTH AMERICA INC.', 'PALM BAY INTERNATIONAL INC',
       'REMY COINTREAU USA INC', 'SIDNEY FRANK IMPORTING CO',
       'E & J GALLO WINERY', 'WILLIAM GRANT & SONS INC',
       'HEAVEN HILL DISTILLERIES', 'DISARONNO INTERNATIONAL LLC',
       'EDRINGTON AMERICAS', 'CASTLE BRANDS CORP.',
       'SOUTHERN WINE & SPIRITS NE', 'STE MICHELLE WINE ESTATES',
       'TRINCHERO FAMILY ESTATES', 'MHW LTD', 'WINE GROUP INC',
       'PERFECTA WINES', 'LUXCO INC', 'TREASURY WINE ESTATES',
       'DIAGEO CHATEAU ESTATE WINES', 'SHAW ROSS INT L IMP LTD',
       'PINE STATE TRADING CO', 'PHILLIPS PRODUCTS CO.',
       'CALEDONIA SPIRITS INC', 'STATE WINE & SPIRITS',
       'KOBRAND CORPORATION', 'BANFI PRODUCTS CORP',
       'VINEYARD BRANDS INC', 'DELICATO VINEYARDS INC',
       'FABRIZIA SPIRITS LLC', 'DUGGANS DISTILLED PRODUCTS',
       'Serralles Usa LLC', 'SEA HAGG DISTILLERY LLC',
       'OLE SMOKY DISTILLERY LLC', 'VRANKEN AMERICA', 'KLIN SPIRITS LLC',
       'LAIRD & CO', 'ADAMBA IMPORTS INTL INC',
       'LATITUDE BEVERAGE COMPANY', 'FREDERICK WILDMAN & SONS',
       'MCCORMICK DISTILLING CO', 'CHARLES JACQUIN ET CIE INC',
       'WESTERN SPIRITS BEVERAGE CO', 'MARSALLE COMPANY',
       'AMERICAN VINTAGE BEVERAGE', 'MANGO BOTTLING INC',
       'SWEET BABY VINEYARD', 'NICHE W & S', 'LABELLE VYDS AND WINERY',
       'FLAG HILL WINERY & VINEYARD', 'SMOKY QUARTZ DISTILLERY LLC',
       'PREMIUM PORT WINES, INC.', 'Russian Standard Vodka',
       'Dunn Wine Brokers', 'WEIN BAUER INC', 'BULLY BOY DISTILLERS',
       'ATLANTIC IMPORTING COMPANY', 'PREMIER DISTRIBUTORS',
       'VINILANDIA USA', 'PARK STREET IMPORTS LLC', 'TAKARA SAKE USA INC',
       'SEA BREEZE CELLARS LLC', 'STARK BREWING COMPANY', 'TY KU LLC',
       'PSP WINES', 'TAMWORTH DISTILLING', 'ZORVINO VINEYARDS',
       'SOUTHERN GLAZERS W&S OF NE', 'HOOD RIVER DISTILLERS, Inc.',
       'CRUSH WINES', 'POVERTY LANE ORCHARDS', 'DJINN SPIRITS LLC',
       'MOONLIGHT MEADERY', 'TALL SHIP DISTILLERY LLC',
       'FORTUNE WINE BROKERS LLC', 'BLACK COVE BEVERAGES', 'VINEXTRA INC',
       'SURVILLE ENTERPRISES CORP', 'JEWELL TOWNE VINEYARDS',
       'SWEETWATER FARM', 'ALTAMAR BRANDS LLC', 'CANDIA VINEYARDS',
       'INCREDIBREW INC', 'ALISA CARR BEVERAGES',
       'STELLAR IMPORTING CO LLC', 'FULCHINO VINEYARD INC',
       'IRA GOLDMAN AND WILLIAMS, LLP', 'Circa Wines',
       'VINEDREA WINES LLC', 'BLACK PRINCE DISTILLERY INC',
       'VINEYARD BRANDS LLC', 'THE IMPORTED GRAPE LLC',
       'WALPOLE MTN VIEW WINERY', 'GILMANTON WINERY & VINEYARD',
       'HAUNTING WHISPER VYDS', 'STAR INDUSTRIES INC.',
       'LOYAL DOG WINERY', 'R.P.IMPORTS INC', 'THE PIERPONT GROUP LLC',
       'APPOLO VINEYARDS LLC', 'BLACK ROCK SPIRITS LLC',
       'CENTEUR IMPORTS LLC', 'HIGHLAND WINE MERCHANTS LLC',
       'AMERICAN SPIRITS EXCHANGE', 'UNCORKED', 'BRONCO WINE COMPANY',
       'MILTONS DISTRIBUTING CO', 'TRUETT HURST', 'LAUREATE IMPORTS CO',
       'FANTASY FINE WINES CORP', 'AAPER ALCOHOL & CHEMICAL CO',
       'SILVER MOUNTAIN CIDERS', 'CAPSTONE INTERNATIONAL',
       'FLAVOR ESSENCE INC'], dtype=object)

In [40]:
vendor_sales_summary ['Description' ].unique()

array(['Jack Daniels No 7 Black', "Tito's Handmade Vodka",
       'Absolut 80 Proof', ..., 'Crown Royal Apple',
       'Concannon Glen Ellen Wh Zin', 'The Club Strawbry Margarita'],
      shape=(9651,), dtype=object)

### Data Wrangling

In [35]:
vendor_sales_summary ['Volume' ] = vendor_sales_summary['Volume' ]. astype('float64')

In [36]:
vendor_sales_summary.fillna(0, inplace = True)

In [37]:
vendor_sales_summary ['VendorName' ] = vendor_sales_summary ['VendorName'].str.strip()
# remove the leading and trailing spaces from the VendorName column

In [41]:
vendor_sales_summary ['GrossProfit'] = vendor_sales_summary ['TotalSalesDollars' ] - vendor_sales_summary ['TotalPurchaseDollars' ]

In [42]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68,1290667.91
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24,1015032.27
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22,1119816.92
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07,1214774.94
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07,1199901.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750.0,2,2.64,5.0,15.95,10.96,0.55,27100.41,13.31
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50.0,6,2.34,134.0,65.66,1.47,7.04,50293.62,63.32
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50.0,2,1.48,2.0,1.98,0.99,0.10,14069.87,0.50
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200.0,1,1.47,72.0,143.28,77.61,15.12,257032.07,141.81
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50.0,1,0.71,86.0,85.14,33.66,4.46,38994.78,84.43

In [44]:
vendor_sales_summary['GrossProfit'].min()

np.float64(-52002.780000000006)

In [45]:
vendor_sales_summary ['ProfitMargin' ] = (vendor_sales_summary['GrossProfit'] / vendor_sales_summary['TotalSalesDollars'])*100

In [46]:
vendor_sales_summary ['StockTurnover' ] = vendor_sales_summary ['TotalSalesQuantity']/vendor_sales_summary['TotalPurchaseQuantity']

In [47]:
vendor_sales_summary ['SalestoPurchaseRatio' ] = vendor_sales_summary ['TotalSalesDollars']/vendor_sales_summary ['TotalPurchaseDollars']

In [49]:
vendor_sales_summary.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'Description', 'PurchasePrice',
       'ActualPrice', 'Volume', 'TotalPurchaseQuantity',
       'TotalPurchaseDollars', 'TotalSalesQuantity', 'TotalSalesDollars',
       'TotalSalesPrice', 'TotalExciseTax', 'FreightCost', 'GrossProfit',
       'ProfitMargin', 'StockTurnover', 'SalestoPurchaseRatio'],
      dtype='object')

### saving table in DB

In [48]:
# saving table
cursor = conn.cursor()

In [50]:
cursor.execute("""CREATE TABLE vendor_sales_summary ( 
               VendorNumber INT, 
               VendorName VARCHAR(100), 
               Brand INT, 
               Description VARCHAR(100),
               PurchasePrice DECIMAL(10,2), 
               ActualPrice DECIMAL(10,2), 
               Volume , 
               TotalPurchaseQuantity INT, 
               TotalPurchaseDollars DECIMAL(15,2), 
               TotalSalesQuantity INT, TotalSalesDollars DECIMAL(15,2), 
               TotalSalesPrice DECIMAL(15,2), 
               TotalExciseTax DECIMAL(15,2), 
               FreightCost DECIMAL(15,2), 
               GrossProfit DECIMAL(15,2), 
               ProfitMargin DECIMAL(15,2), 
               StockTurnover DECIMAL(15,2), 
               SalesToPurchaseRatio DECIMAL(15,2), 
               PRIMARY KEY (VendorNumber, Brand)

)""")

In [ ]:
pd.read_sql("SELECT * FROM vendor_sales_summary", conn) # creating a empyt table to store the final output

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750.0,2,2.64,5.0,15.95,10.96,0.55,27100.41,13.31,83.448276,2.500000,6.041667
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50.0,6,2.34,134.0,65.66,1.47,7.04,50293.62,63.32,96.436186,22.333333,28.059829
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50.0,2,1.48,2.0,1.98,0.99,0.10,14069.87,0.50,25.252525,1.000000,1.337838
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200.0,1,1.47,72.0,143.28,77.61,15.12,257032.07,141.81,98.974037,72.000000,97.469388
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50.0,1,0.71,86.0,85.14,33.66,4.46,38994.78,84.43,99.166079,86.000000,119.915493

In [ ]:
vendor_sales_summary.to_sql('vendor_sales_summary', conn, if_exists = 'replace', index = False )
# pushing to empty table in the database

10692